[package]
name = "rusty-ls"
version = "0.1.0"
authors = ["Felix Wolff <felix-registrations@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
